/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2020-01-23 17:22:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class addFav_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

final boolean DEBUG = false;
	String db 		= "interapp";
	String user 	= "interapp";
	String passwd	= "oH3C7!Jo5PZw5Zfc";
	
	Connection conn = null;
	Statement stmt	= null;
	Statement stmt2 = null;
	Statement stmt3 = null;
	Statement stmt4 = null;
	Statement stmt5	= null;
	ResultSet rs	= null;
	ResultSet rs2 	= null;
	ResultSet rs3	= null;
	ResultSet rs4	= null;
	
	String sql 		= null;
	String sql2		= null;
	String sql3		= null;
	String sql4		= null;
	String sql5		= null;
	
	String name		= null;
	String sd		= null;
	
	Integer dID 	= null;
	Integer depID	= null;
	Integer eID		= null;
	Integer uID		= null;
	
	String eram		= null;
	String edel		= null;
	String edep		= null;
	String esec		= null;
	String nequipo	= null;
	
	name = request.getParameter("favorito") == null ? "": request.getParameter("favorito");
	sd = request.getParameter("seed") == null ? "": request.getParameter("seed");
	
	name = name.trim();
	
	try
	{
		Class.forName("org.gjt.mm.mysql.Driver");
		conn = DriverManager.getConnection("jdbc:mysql://arkesol.ddnsfree.com/" + db, user, passwd);
		
		stmt 	= conn.createStatement();
		stmt2 	= conn.createStatement();
		stmt3 	= conn.createStatement();
		stmt4	= conn.createStatement();
		stmt5	= conn.createStatement();
		
		sql		= "SELECT delegaciones_id FROM delegaciones WHERE Nombre = '"+name+"'";
		sql2	= "SELECT deporte_id FROM deporte WHERE Descripcion = '"+name+"'";
		sql3	= "SELECT e.equipo_id, r.Descripcion AS 'Rama', d.Codigo AS 'Delegacion', de.Descripcion AS 'Deporte', s.Descripcion AS 'Seccion' FROM equipo e, rama r, delegaciones d, deporte de, seccion s WHERE d.delegaciones_id = e.ID_D AND de.deporte_id = e.ID_De AND r.rama_id = e.ID_R AND s.seccion_id = e.ID_S";
		sql4	= "SELECT usuario_id FROM usuario WHERE Seed = '"+sd+"'";
		
		System.out.println(sql);
		
		rs 	= stmt.executeQuery(sql);
		rs2	= stmt2.executeQuery(sql2);
		rs3	= stmt3.executeQuery(sql3);
		rs4	= stmt4.executeQuery(sql4);
		
		if(rs.next()){
			dID = rs.getInt("delegaciones_id");
		}
		
		if(rs2.next()){
			depID = rs2.getInt("deporte_id");
		}
		
		while(rs3.next()){
			eram = rs3.getString("Rama");
			edel = rs3.getString("Delegacion");
			edep = rs3.getString("Deporte");
			esec = rs3.getString("Seccion");
			
			nequipo = edel+" "+edep+" "+eram+" "+esec;
			
			System.out.println("Seleccionado "+nequipo);
			System.out.println("Favorito "+name);
			
			nequipo = nequipo.trim();
			
			boolean comp = nequipo.equals(name);
			System.out.println(comp);
			
			if(comp){
				System.out.println("Entre a la condicion");
				eID = rs3.getInt("equipo_id");
			}
		}
		
		if(rs4.next()){
			uID = rs4.getInt("usuario_id");
		}
		
		sql5 = "INSERT INTO favorito_del_usuario (ID_U, ID_D, ID_Eq, ID_De) VALUES ("+uID+", "+dID+", "+eID+", "+depID+")";
		System.out.println(sql5);
		
		stmt5.executeUpdate(sql5);
		
	}
	catch(SQLException e)
	{
		out.println("SQLException caught: " + e.getMessage());
	}
	finally
	{
		try{rs.close();} catch(Exception e){}
		try{stmt.close();} catch(Exception e){}
		try{rs2.close();} catch(Exception e){}
		try{stmt2.close();} catch(Exception e){}
		try{rs3.close();} catch(Exception e){}
		try{stmt3.close();} catch(Exception e){}
		try{stmt4.close();} catch(Exception e){}
		try{stmt5.close();} catch(Exception e){}
		try{conn.close();} catch(Exception e){}
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
