/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2020-09-08 18:38:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.solucionesenjambre.interapp.fs.dto.Rounds;
import com.solucionesenjambre.interapp.tier.RoundsTier;
import com.solucionesenjambre.interapp.fs.dto.Courts;
import com.solucionesenjambre.interapp.tier.CourtsTier;
import com.solucionesenjambre.interapp.fs.dto.Events;
import com.solucionesenjambre.interapp.tier.EventsTier;
import com.solucionesenjambre.interapp.fs.dto.Branches;
import com.solucionesenjambre.interapp.tier.BranchesTier;
import com.solucionesenjambre.interapp.fs.dto.VwSchools;
import com.solucionesenjambre.interapp.fs.dto.VwSports;
import com.solucionesenjambre.interapp.tier.VwSchoolsTier;
import com.solucionesenjambre.interapp.tier.VwSportsTier;
import com.solucionesenjambre.interapp.fs.dto.Schools;
import com.solucionesenjambre.interapp.tier.SchoolsTier;
import com.solucionesenjambre.interapp.fs.dto.Sports;
import java.util.List;
import com.solucionesenjambre.interapp.tier.SportsTier;
import com.solucionesenjambre.interapp.fs.jdbc.ResourceManager;
import java.sql.*;

public final class IntersPartidos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>IS | Registro de Partidos</title>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"aaaCssGeneralInterWebApp.css\">\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body style=\"margin: 0; padding: 0;\">\r\n");
      out.write("\t\t<h1 class=\"Titulo\">Registro de Partidos.</h1>\r\n");
      out.write("\t\t<form action=\"Partidos.jsp\" method=\"post\">\r\n");
      out.write("\t\t");
 
		
			HttpSession sesion = request.getSession();
			String eId = sesion.getAttribute("eid").toString();
			int eventId = Integer.parseInt(eId);
		
			VwSportsTier vwSportsTier = new VwSportsTier(); 
			List<VwSports> sports = null;
			
			VwSchoolsTier vwSchoolsTier = new VwSchoolsTier();
			List<VwSchools> schools = null;
			
			BranchesTier branchesTier = new BranchesTier();
			List<Branches> branches = null;
			
			EventsTier eventsTier = new EventsTier();
			Events events = null;
			
			CourtsTier courtsTier = new CourtsTier();
			List<Courts> courts = null;
			
			RoundsTier roundsTier = new RoundsTier();
			List<Rounds> rounds = null;
		
			String name = null;
			int value = 0;
			
			try
			{				
				sports = vwSportsTier.getByEvent(eventId);
				branches = branchesTier.all();
				courts = courtsTier.all();		
				schools = vwSchoolsTier.getByEvent(eventId);
				events = eventsTier.get(eventId);
				rounds = roundsTier.all();
				
				out.println("<select style=\"position: absolute; top: 25%; left: 15%; height: 8%;\" id=\"disciplina\" name=\"disciplina\">	<option selected>--Selecciona un deporte--</option>");
				for(VwSports sport : sports){
					name = sport.getDescription();
					value = sport.getSportId();
					out.println("<option value=\""+ value +"\">"+name+"</option>");
				} out.println("</select>");
				
				out.println("<select style=\"position: absolute; top: 25%; left: 40%; height: 8%;\" id=\"rama\" name=\"rama\">	<option selected>--Selecciona una rama--</option>");
				for(Branches branch : branches){
					name = branch.getDescription();
					value = branch.getBranchId();
					out.println("<option value=\"" + value + "\">" + name + "</option>");
				} out.println("</select>");
				
				out.println("<select style=\"position: absolute; top: 49%; left: 15%; height: 8%;\" id=\"cancha\" name=\"cancha\"> <option selected>--Selecciona una cancha--</option>");
				for(Courts court : courts){
					name = court.getDescription();
					value = court.getCourtId();
					out.println("<option value=\"" + value + "\">" + name + "</option>");
				} out.println("</select>");
				
				out.println("<select style=\"position: absolute; top: 70%; left: 27%; height: 8%;\" id=\"local\" name=\"local\"> <option selected>--Selecciona un equipo--</option>");
				for(VwSchools school : schools){
					name = school.getDescription();
					value = school.getSchoolId();
					out.println("<option value=\"" + value + "\">" + name + "</option>");
				} out.println("</select>");
				
				out.println("<select style=\"position: absolute; top: 70%; left: 55%; height: 8%;\" id=\"visitante\" name=\"visitante\">	<option selected>--Selecciona un equipo--</option>");
				for(VwSchools school : schools){
					name = school.getDescription();
					value = school.getSchoolId();
					out.println("<option value=\"" + value + "\">" + name + "</option>");
				} out.println("</select>");
				
				out.println("<select style=\"position: absolute; top: 25%; left: 65%; height: 8%;\" id=\"seccion\" name=\"seccion\">		<option selected>--Selecciona un evento--</option>");
				{
					name = events.getEventName();
					value = events.getEventId();
					out.println("<option selected value=\"" + value + "\">" + name + "</option>");
				} out.println("</select>");
				
				out.println("<select style=\"position: absolute; top: 70%; left: 2.5%; height: 8%;\" id=\"ronda\" name=\"ronda\">		<option selected>--Selecciona una Ronda--</option>");
				for(Rounds round : rounds){
					name = round.getDescription();
					value = round.getRoundId();
					out.println("<option value=\"" + value + "\">" + name + "</option>");
				} out.println("</select>");
			}
			finally {}
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--Disciplina-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 15%; left: 15%;\"><b></b>Disciplina</h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--Rama-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 15%; left: 40%;;\"><b>Rama</b></h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!--Seccion-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 15%; left: 65%;\"><b>Seccion</b></h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<!--Cancha-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 38.5%; left: 15%;\"><b>Cancha</b></h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!--Parsear la hora o introducir opciones-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--Dia-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 40%; left: 46%;\"><b>Dia</b></h2>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input class=\"InputGeneral\" placeholder=\"dd\" style=\"position: absolute; top: 49%; left: 44.5%; height: 6%; width: 5.5%; font-size:1em;\" id=\"dia\" name = \"dia\">\r\n");
      out.write("\t\t\t<input class=\"InputGeneral\" placeholder=\"mm\" style=\"position: absolute; top: 49%; left: 51%; height: 6%; width: 5.5%; font-size:1em;\" id=\"mes\" name = \"mes\">\r\n");
      out.write("\t\t\t<input class=\"InputGeneral\" placeholder=\"yyyy\" style=\"position: absolute; top: 49%; left: 57.5%; height: 6%; width: 7%; font-size:1em;\" id=\"ano\" name = \"ano\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Hora -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 40%; left: 70%;\"><b>Hora (24 hrs)</b></h2>\r\n");
      out.write("\t\t\t<input placeholder=\"hh\" style=\"position: absolute; top: 49%; left: 70.8%; height: 6%; width: 5.5%; font-size:1em;\" id=\"hora\" name = \"hora\">\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos1\" style=\"position: absolute; top: 46%; left: 77.2%;\"><b>:</b></h2>\r\n");
      out.write("\t\t\t<input placeholder=\"mm\" style=\"position: absolute; top: 49%; left: 78.2%; height: 6%; width: 5.5%; font-size:1em;\" id=\"minutos\" name = \"minutos\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--Contrincantes-->\r\n");
      out.write("\t\t<!--Local-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 60%; left: 35%;\"><b>Local</b></h2>\t\r\n");
      out.write("\t\t<!--Visitante-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 60%; left: 57%;\"><b>Visitante</b></h2>\r\n");
      out.write("\t\t<!--Versus-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 69%; left: 51%;\"><b>VS</b></h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--Ronda-->\r\n");
      out.write("\t\t\t<h2 class=\"subtitulos\" style=\"position: absolute; top: 60%; left: 5%;\"><b>Ronda</b></h2>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--Button-->\r\n");
      out.write("\t\t\t<button type=\"submit\" style=\"position: absolute;width: 15%; height: 9%;left: 43%; top: 85%;\">Registrar</button>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
