/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2020-03-10 19:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.anahuac.garibaldi.fs.jdbc.ResourceManager;
import java.sql.*;

public final class IntersRegistro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>IS | Registro de Jugadores</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"aaaCssGeneralInterWebApp.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--Titulo-->\r\n");
      out.write("\t<h1 class=\"Titulo\">Registro de Jugadores</h1>\r\n");
      out.write("\t<form action=\"Registro.jsp\" method=\"post\">\r\n");
      out.write("\t\r\n");
      out.write("\t");

	String db="interapp";
	String usuario="interapp";
	String passwd="oH3C7!Jo5PZw5Zfc";
	
	Connection conn=null;
	Statement stmt=null;
	
	ResultSet rs=null;
	
	String sql=null;
	
	String delegacion=null;
	int equipoId;
	int equipoIdLocal;
	String equipoIdPost;
	
	equipoIdPost = request.getParameter("equipoId") == null ? "0" : request.getParameter("equipoId");
	
	equipoIdLocal = Integer.parseInt(equipoIdPost);
	
	try{
		
		conn = ResourceManager.getConnection();
		
		stmt=conn.createStatement();
		
		sql="SELECT * FROM vw_equipos";
		
	//<!--delegacion-->
	rs=stmt.executeQuery(sql);
		out.println("	<select  type=\"text\" id=\"equipo\" name=\"equipo\" placeholder=\"EQUIPO\" style=\"position: absolute; width: 30%;height: 10%;left: 51%;top: 28%;\"><option selected>EQUIPO</option>");
		while(rs.next()){
			delegacion=rs.getString("nombre_equipo");
			equipoId = rs.getInt("equipo_id");
			if(equipoIdLocal == equipoId){
				out.println("		<option selected value=\""+ equipoId +"\">"+delegacion+"</option>");
			}else{
				out.println("		<option value=\""+ equipoId +"\">"+delegacion+"</option>");
			}
		}
		out.println("	</select>");
	
}	
	
	catch(SQLException e)
	{
		out.println("SQLException caught: " + e.getMessage());
	}
	finally
	{
		try{rs.close();} catch(Exception e){}
		try{stmt.close();} catch(Exception e){}	
		try{conn.close();} catch(Exception e){}
	}
	
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!--Nombres-->\r\n");
      out.write("\t<input type=\"text\" id=\"nombres\" name=\"nombres\" placeholder=\"NOMBRES\" style=\"position: absolute; width: 25%;height: 8%;left: 18%;top: 20%; font-size: 2em;\">\r\n");
      out.write("\r\n");
      out.write("\t<!--PRIMER APELLIDO-->\r\n");
      out.write("\t<input class=\"General\" type=\"text\" id=\"PrimerApellido\" name= \"PrimerApellido\" placeholder=\"PRIMER APELLIDO\" style=\"position: absolute; width: 25%;height: 8%;left: 18%;top: 38%; font-size: 2em;\">\r\n");
      out.write("\r\n");
      out.write("\t<!--Segundo APELLIDO-->\r\n");
      out.write("\t<input class=\"General\" type=\"text\" id=\"SegundoApellido\" name=\"SegundoApellido\" placeholder=\"SEGUNDO APELLIDO\" style=\"position: absolute; width: 25%;height: 8%;left:18%;top: 56%; font-size: 2em;\">\r\n");
      out.write("\r\n");
      out.write("\t<!--numero-->\r\n");
      out.write("\t<input class=\"General\" type=\"text\" id=\"numero\" name=\"numero\" placeholder=\"NUMERO\" style=\"position: absolute; width: 25%;height: 8%;left: 18%;top: 74%; font-size: 2em;\">\r\n");
      out.write("\r\n");
      out.write("\t<!--Boton-->\r\n");
      out.write("\t<button class=\"General\" type=\"submit\" style=\"position: absolute;width: 15%; height: 9%;left: 58%; top: 50%;\">Registrar</button>\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
