/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2020-01-30 13:42:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LogIn_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

final boolean DEBUG = true;
String us = "";
String pw = "";
if (DEBUG)
{
	us = "capturista";
	pw = "cap";
}

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Intersalesianos|Log In</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"aaaCssGeneralInterWebApp.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!--Titulo-->\r\n");
      out.write("\t<h1 class= \"Titulo\">intersalesianos</h1> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--Usuario-->\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t\t<p class=\"subtitulos\" style=\"position: absolute; top:20%; left:41%; font-size: 1.55em;\">Nombre de Usuario</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--Contraseña-->\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t\t<p class=\"subtitulos\" style=\"position: absolute; top:40%; left:41%; font-size: 1.55em;\">Contraseña</p>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("<form action=\"LogInFile.jsp\" method=\"post\">\r\n");
      out.write("<input type=\"text\" style=\"position: absolute; width: 20%; height: 50px; top: 28%; left: 40%;\" placeholder=\"Enter Username\" name=\"us\" id=\"us\" value=");
      out.print(us );
      out.write(">\r\n");
      out.write("<br/>\r\n");
      out.write("<input type=\"text\" style=\"position: absolute; width: 20%; height: 50px; top: 48%; left: 40%;\" placeholder=\"Contraseña\" name=\"pw\" id=\"pw\" value=");
      out.print(pw );
      out.write(">\r\n");
      out.write("<br/>\r\n");
      out.write("<button type=\"submit\" style=\"position: absolute; width: 11%; height: 6%; top: 65%; left: 52.5%; font-size: .9em;\">Login</button>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
