/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2020-09-08 14:44:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.solucionesenjambre.interapp.fs.dto.Users;
import com.solucionesenjambre.interapp.tier.UsersTier;
import com.solucionesenjambre.interapp.fs.jdbc.ResourceManager;
import java.util.*;
import java.sql.*;

public final class LogInFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("   <head>\r\n");
      out.write("      <title>Intersalesianos</title>\r\n");
      out.write("      <link rel=\"stylesheet\" type=\"text/css\" href=\"aaaCssGeneralInterWebApp.css\">\r\n");
      out.write("   </head> \r\n");
      out.write("   <body>\r\n");
      out.write("    \t<!-- Barra superior -->\r\n");
      out.write("\t\t<h1 class= \"Titulo\">INTERAPP</h1> \r\n");
      out.write("\t\r\n");
      out.write("    <!-- Div -->\r\n");
      out.write("    <div>\r\n");
      out.write("\r\n");

final boolean DEBUG = false;
	
	String sql 		= null;
	String prnt 	= "<br/>Usuario o contraseña incorrectos";
	int t 			= 0;
	int id 			= 0;
	int eid			= 0;
	String us 		= null;
	String pw = null;
	
	us = request.getParameter("us") == null ? "": request.getParameter("us");
	pw = request.getParameter("pw") == null ? "": request.getParameter("pw");
	
	HttpSession sesion = request.getSession();
	
	try
	{		
		UsersTier tier = new UsersTier();
		List<Users> usuarios = tier.findUser(us, pw);
		
		for (Users users : usuarios)
		{
			t  	= users.getUserTypeId();
			id 	= users.getUserId();
			eid = users.getEventId();
			sesion.setAttribute("eid", eid);
			sesion.setAttribute("idr", id);
			sesion.setAttribute("tr",t);
		}
		String servidor = "http://" + request.getServerName()+ ":" + request.getServerPort()+ "/interapps/";
		String pagina;
		
		switch (t)
		{
			case 1:
				pagina = "./MenuPrincipal.html";
		    	response.sendRedirect(pagina);
				break;
			case 2:
				pagina = "./IntersRegistro.jsp";
			    response.sendRedirect(pagina);
				break;
			default:
				out.println("<br/><button type= \"button\" class = \"logInButton\" style = \"position: absolute;width: 22%;height: 25%; top: 46%; left: 39%;font-family:Roboto Slab;font-style: normal;font-size: 1.25em;\" href=\"#\" onclick=\"javascript:window.history.back();\"> " + prnt + " volver</a>");
				break;
		}
		
	}finally{}

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
