/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2020-06-09 16:38:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.solucionesenjambre.interapp.tier.NewsTier;
import com.solucionesenjambre.interapp.fs.jdbc.ResourceManager;
import java.sql.*;

public final class news_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	final boolean DEBUG = false;
	
	String title = request.getParameter("Titulo") == null ? "" : request.getParameter("Titulo");
	String img = request.getParameter("img") == null ? "" : request.getParameter("img");
	String desc = request.getParameter("desc") == null ? "" : request.getParameter("desc");
	String erid = request.getParameter("eid") == null ? "" : request.getParameter("eid");
	
	int eid = Integer.parseInt(erid);
	
	String pagina1	= "./IntersNews.jsp";
	
	String serverImage = "https://solucionesenjambre.com/interapp/imagenes/";
	
	img = serverImage + img;
	System.out.println(desc);
	
	try
	{
		NewsTier tier = new NewsTier();
		
		boolean insertion = tier.set(img, desc, eid, title);
		
		if(insertion)
		{
			out.println("<!DOCTYPE html>");
			out.println("<html>");	
			out.println("	<head>");
			out.println("		<title>IS | Noticias</title>");			
			out.println("		<link rel=\"stylesheet\" type=\"text/css\" href=\"aaaCssGeneralInterWebApp.css\">");				
			out.println("	</head>");
			out.println("	<body>");
			out.println("		<div class=\"Aviso\" style=\"top: 35%; left: 20%;\">");
			out.println("			<div>Noticia registrada con exito</div>");
			out.println("			<a  href=\"./IntersNews.jsp\"><button class=\"BotonAviso\" style=\"position: absolute; left: 15%; top: 50%;\">Registrar Otra</button></a>");
			out.println("		</div>");
			out.println("	</body>");	
			out.println("</html>");
		}
		else
		{
			out.println("<!DOCTYPE html>");
			out.println("<html>");	
			out.println("	<head>");
			out.println("		<title>IS | Noticias</title>");			
			out.println("		<link rel=\"stylesheet\" type=\"text/css\" href=\"aaaCssGeneralInterWebApp.css\">");				
			out.println("	</head>");
			out.println("	<body>");
			out.println("		<div class=\"Aviso\" style=\"top: 35%; left: 20%;\">");
			out.println("			<div>Noticia registrada con exito</div>");
			out.println("			<button class=\"BotonAviso\" style=\"position: absolute; left: 15%; top: 50%;\" href=\"#\" onclick=\"javascript:window.history.back();\">Registrar Otra</button>");
			out.println("		</div>");
			out.println("	</body>");	
			out.println("</html>");
		}
	}
	finally{}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
