/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2020-09-09 14:55:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.DateFormat;
import com.solucionesenjambre.interapp.tier.TeamsTier;
import com.solucionesenjambre.interapp.tier.GamesTier;
import com.solucionesenjambre.interapp.fs.dto.Teams;
import com.solucionesenjambre.interapp.fs.dto.VwTeams;
import com.solucionesenjambre.interapp.tier.VwTeamsTier;
import com.solucionesenjambre.interapp.fs.jdbc.ResourceManager;

public final class Partidos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	final boolean DEBUG	= false;

	GamesTier gamesTier = new GamesTier();
	boolean insert;
	
	TeamsTier teamsTier = new TeamsTier();

	String[] team1 = new String[4];
	String[] team2 = new String[4];
	
	int team1Id;
	int team2Id;
	
	DateFormat dateFormat = new SimpleDateFormat("dd mm yyyy");
	DateFormat hourFormat = new SimpleDateFormat("HH:mm");
	
	Date date;
	Date time;
	
	String disciplina	= null;
	String rama			= null;
	String local		= null;
	String visitante	= null;
	String cancha		= null;
	String hora			= null;
	String seccion		= null;
	String ronda		= null;
	
	String minutos;
	String dia;
	String mes;
	String año;
	
	String fecha;
	String tiempo;
	
	disciplina = request.getParameter("disciplina") == null ? "": request.getParameter("disciplina");
	rama = request.getParameter("rama") == null ? "": request.getParameter("rama");
	local = request.getParameter("local") == null ? "": request.getParameter("local");
	visitante = request.getParameter("visitante") == null ? "": request.getParameter("visitante");
	cancha = request.getParameter("cancha") == null ? "": request.getParameter("cancha");
	hora = request.getParameter("hora") == null ? "": request.getParameter("hora");
	dia = request.getParameter("dia") == null ? "": request.getParameter("dia");
	mes = request.getParameter("mes") == null ? "": request.getParameter("mes");
	año = request.getParameter("ano") == null ? "": request.getParameter("ano");
	minutos = request.getParameter("minutos") == null ? "": request.getParameter("minutos");
	seccion = request.getParameter("seccion") == null ? "": request.getParameter("seccion");
	ronda = request.getParameter("ronda") == null ? "": request.getParameter("ronda");
	
	if (DEBUG)
	{
		out.println("<br/>disciplina [" + disciplina + "]");
		out.println("<br/>rama [" + rama + "]");
		out.println("<br/>local [" + local + "]");
		out.println("<br/>visitante [" + visitante + "]");
		out.println("<br/>cancha [" + cancha + "]");
		out.println("<br/>hora [" + hora + "]");
		out.println("<br/>seccion [" + seccion + "]");
	}
	
	try
	{		
		team1[0] = local;
		team1[1] = disciplina;
		team1[2] = rama;
		team1[3] = seccion;
		
		team2[0] = visitante;
		team2[1] = disciplina;
		team2[2] = rama;
		team2[3] = seccion;
		
		team1Id = teamsTier.findId(team1);
		team2Id = teamsTier.findId(team2);
		
		fecha = dia + " " + mes + " " + año;
		date = dateFormat.parse(fecha);
		
		tiempo = hora + ":" + minutos;
		time = hourFormat.parse(tiempo);
		
		insert = gamesTier.set(Integer.parseInt(cancha), date, time, team1Id, team2Id, Integer.parseInt(ronda));
			
		if(insert)
		{
			out.println("<!DOCTYPE html>");
			out.println("<html>");	
			out.println("	<head>");
			out.println("		<title>resultado</title>");			
			out.println("		<link rel=\"stylesheet\" type=\"text/css\" href=\"aaaCssGeneralInterWebApp.css\">");				
			out.println("	</head>");
			out.println("	<body>");
			out.println("		<div class=\"Aviso\" style=\"top: 35%; left: 20%;\">");
			out.println("			<div>Partido registrado con exito</div>");
			out.println("			<a  href=\"./IntersPartidos.jsp\"><button class=\"BotonAviso\" style=\"position: absolute; left: 15%; top: 50%;\">Registrar otro</button></a>");
			out.println("			<a  href=\"./MenuPrincipal.jsp\"><button class=\"BotonAviso\" style=\"position: absolute; left: 55%; top: 50%;\">menu principal</button></a>");
			out.println("		</div>");
			out.println("	</body>");	
			out.println("</html>");
		}
		else
		{
			out.println("<!DOCTYPE html>");
			out.println("<html>");	
			out.println("	<head>");
			out.println("		<title>resultado</title>");			
			out.println("		<link rel=\"stylesheet\" type=\"text/css\" href=\"aaaCssGeneralInterWebApp.css\">");				
			out.println("	</head>");
			out.println("	<body>");
			out.println("		<div class=\"Aviso\" style=\"top: 35%; left: 20%;\">");
			out.println("			<div>Problema al registrar el partido</div>");
			out.println("			<a  href=\"./IntersPartidos.jsp\"><button class=\"BotonAviso\" style=\"position: absolute; left: 15%; top: 50%;\">Registrar otro</button></a>");
			out.println("			<a  href=\"./MenuPrincipal.jsp\"><button class=\"BotonAviso\" style=\"position: absolute; left: 55%; top: 50%;\">menu principal</button></a>");
			out.println("		</div>");
			out.println("	</body>");	
			out.println("</html>");
		}
	}
	finally{}

      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
