/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.27
 * Generated at: 2020-01-30 14:09:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class Registro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	boolean DEBUG	= false;

	String db      	= "interapp";
	String usuario 	= "interapp";
	String passwd  	= "oH3C7!Jo5PZw5Zfc";
	
	Connection conn			= null;
	Statement stmt  		= null;
	String sql2 			= null;
	
	String delegacion      	= null;
	String deporte         	= null;
	String seccion         	= null;
	String rama            	= null;
	String nombres         	= null;
	String PrimerApellido  	= null;
	String SegundoApellido 	= null;
	
	int entero				= 0;
	int numero				= 0;
	String numeroStr;
	
	delegacion	    =	request.getParameter("equipo") == null ? "": request.getParameter("equipo");
	nombres 	    =	request.getParameter("nombres") == null ? "": request.getParameter("nombres");
	PrimerApellido	=	request.getParameter("PrimerApellido") == null ? "": request.getParameter("PrimerApellido");
	SegundoApellido	=	request.getParameter("SegundoApellido") == null ? "": request.getParameter("SegundoApellido");
	numeroStr		= 	request.getParameter("numero")	== null ? "": request.getParameter("numero");
	
	try{
		numero = Integer.parseInt(numeroStr);
	}
	catch(Exception e){}
	try{
		Class.forName("org.gjt.mm.mysql.Driver");
		conn=DriverManager.getConnection("jdbc:mysql://arkesol.ddnsfree.com/"+db,usuario,passwd);
		
		stmt=conn.createStatement(); //Nombre, primer_apellido,segundo_apellido,Numero,ID_Eq
		sql2="INSERT INTO jugadores(Nombre,primer_apellido,segundo_apellido,Numero,ID_Eq) VALUES('"+nombres+"','"+PrimerApellido+"','"+SegundoApellido+"',"+numero+","+delegacion+")";
		
		System.out.println(sql2);
		
		stmt.executeUpdate(sql2);
		
		System.out.println("Registro hecho");
		
		String servidor = "";
		String pagina1	= "./IntersRegistro.jsp?equipoId=" + delegacion; // Esta es para volver al registro
		String pagina2	= "./MenuPrincipal.jsp";
		
		System.out.println(servidor+pagina1);
		
		out.println("<!DOCTYPE html>");
		out.println("<html>");	
		out.println("	<head>");
		out.println("		<title>resultado</title>");			
		out.println("		<link rel=\"stylesheet\" type=\"text/css\" href=\"aaaCssGeneralInterWebApp.css\">");				
		out.println("	</head>");
		out.println("	<body>");
		out.println("		<div class=\"Aviso\" style=\"top: 35%; left: 20%;\">");
		out.println("			<div>Jugador registrado con exito</div>");
						

							

							

					
		
		HttpSession sesion = request.getSession();
		int tdu = (Integer)(sesion.getAttribute("tr"));
		
		if(tdu == 1)
		{
			out.println("			<a  href=\"./IntersRegistro.jsp?equipoId=" + delegacion + "\"><button class=\"BotonAviso\" style=\"position: absolute; left: 15%; top: 50%;\">Registrar otro</button></a>");
			out.println("			<a  href=\"./MenuPrincipal.jsp\"><button class=\"BotonAviso\" style=\"position: absolute; left: 55%; top: 50%;\">menu principal</button></a>");
		}
		else
		{
			out.println("			<a  href=\"./IntersRegistro.jsp?equipoId=" + delegacion + "\"><button class=\"BotonAviso\" style=\"position: absolute; left: 15%; top: 50%;\">Registrar otro</button></a>");
		}
		
		out.println("		</div>");
		out.println("	</body>");	
		out.println("</html>");		
		
	}
	catch(SQLException e)
	{
		out.println("SQLException caught: " + e.getMessage());
	}
	finally
	{
		try{stmt.close();} catch(Exception e){}
		try{conn.close();} catch(Exception e){}
	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
